name: yabeta
favicon: null
layout_spectrum: 0.57677
typography_spectrum: 0.33035
title: Site Teste
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3125
  lightness: 0.4375
  saturation: 0.5
  rhythmicContrast: 0.3904432381968945
purpose: []
