name: yabeta
favicon: null
layout_spectrum: 0.5440078894607723
typography_spectrum: 0.6289950089994818
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.7049315646290779
  lightness: 0.9804830607026815
  saturation: 0.04548948328010738
  rhythmicContrast: 0.3904432381968945
purpose: []
